package.jsonの加筆
traPtitech/booQ-v3-UI pull request #27
Opened 2024-02-20 12:37 UTC by E2-genomu

openapi-typescript導入+package.jsonに記載
ただ生成した.tsから型を自動的に決めるコードの実装の仕方が一向にわからない

2024-02-22 16:09 UTC, s9-sukyu commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
これを書くと、手で書いたファイルを含めてすべてのファイルにおいてany型を許容してしまうことになりそうです。
[src/apis/openAPI.ts](https://github.com/traPtitech/booQ-v3-UI/pull/27/files#diff-359cd7a30bccecfbfdf7e23e27a4b14b76d95083fb50b2e27570bd4856ff5ac9) のみでany型を許容しないようにするために、.eslintignore にsrc/apis/openAPI.tsを含めるのがよさそう

2024-02-22 16:19 UTC, Pugma commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
[src/apis/openAPI.ts](https://github.com/traPtitech/booQ-v3-UI/pull/27/files#diff-359cd7a30bccecfbfdf7e23e27a4b14b76d95083fb50b2e27570bd4856ff5ac9)で永久に`any`型が自動生成され続けるので、openAPI.tsのみでany型を許容するほうがパット見良さそう…？
ただ、oneOfが他のところでも使わてている以上、他のファイルでもany型はそこそこ出てきそうな気はします

2024-02-24 14:42 UTC, cp-20 commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
ESLintのoverridesフィールドを使うと良さそうです
https://blog.popweb.dev/programming/javascript/eslint-overrides/

2024-02-24 14:48 UTC, cp-20 reviewed
細かいですが確認お願いします:pray:

2024-02-24 14:48 UTC, cp-20 commented on package.json
> +    "@openapitools/openapi-generator-cli": "^2.9.0",
どこでも使ってないので消していいと思います～

2024-02-24 14:48 UTC, cp-20 commented on src/apis/client.ts
> +  baseUrl: '', //どのURLを参照するかわからなかったので空にした
環境変数から読み込むのが良さそう

2024-02-24 14:48 UTC, cp-20 commented on package.json
> +    "gen-api": "pnpm openapi-typescript https://raw.githubusercontent.com/traPtitech/booQ-v3/main/docs/openapi.yml --output ./src/apis/openAPI.ts"
個人的な好みですが、`openapi.ts`の方が好きです (どっちでも良いです)

2024-02-25 02:46 UTC, cp-20 requested changes
細々としたところで申し訳ないんですが修正お願いします！🙇

2024-02-25 02:46 UTC, cp-20 commented on .eslintrc.js
>        },
ココはいじらなくて良さそうです～

2024-02-25 02:46 UTC, cp-20 commented on .eslintrc.js
> +      ],
overridesの中にoverrides入れてるみたいになってるので修正して欲しいです～

2024-02-25 02:46 UTC, cp-20 commented on .eslintignore
> +openAPI.ts
eslintのoverrides入れてるのでeslintignoreに登録する必要はないです！ (eslintignoreはそもそも全てのlintルールを無視するような設定なので)

2024-02-25 02:46 UTC, cp-20 commented on package.json
> +    "gen-api": "pnpm openapi-typescript https://raw.githubusercontent.com/traPtitech/booQ-v3/main/docs/openapi.yml --output openAPI.ts"
コメント分かりにくくてすいません ><
`src/apis/openapi.ts` (小文字にする) の意味でした！

2024-02-25 02:46 UTC, cp-20 commented on src/apis/client.ts
> +  baseUrl: 'http://localhost:5173/',
よくよく考えたらCORS回避しなきゃなので、`/api`で良さそうです
(`vite.config.ts`の方に`/api`から実際のバックエンドのアドレスにプロキシする)

2024-02-25 02:49 UTC, E2-genomu commented on src/apis/client.ts
> +  baseUrl: 'http://localhost:5173/',
vite.config.tsに追加記載するということ？

2024-02-25 02:52 UTC, E2-genomu commented on .eslintignore
> +openAPI.ts
これは元々overridesの方で加えても何故かanyのエラーを吐くままなのでeslintingnoreに加えた、eslintrc.jsの表記がおかしくないか確認してもらってもよい？

2024-02-25 04:49 UTC, cp-20 commented on src/apis/client.ts
> +  baseUrl: 'http://localhost:5173/',
`vite.config.ts`で今コメントアウトされてるところが対応します！　ただ今はそのまま (`vite.config.ts`を変えない) で良さそうです～

2024-02-25 06:00 UTC, cp-20 approved these changes
良さそうです～　何度も修正提案しちゃってごめんなさい！お疲れさまでした！

2024-02-25 06:00 UTC, merged