RadioButtonとRadioCardの実装
traPtitech/booQ-v3-UI pull request #57
Opened 2024-07-14 14:30 UTC by Nattuki

close #54
close #55

2024-07-15 07:16 UTC, cp-20 requested changes
見た目については文句なしです！　流石です！

ただコードの書き方的なところについてちょっとだけコメントしたのでサッと確認して修正してもらえると嬉しいです！

2024-07-15 07:22 UTC, Nattuki commented on index.html
> +    <script type="module" src="./src/main.ts"></script>
コレ僕のパソコン上でなんか動かなさそうです
後で確認します

2024-07-15 08:04 UTC, Nattuki commented on src/shared/components/RadioButton.vue
`<input type="radio">`に直接スタイルを変更するのなんかうまく行かなかったので`<input>`は`display: none`にしてそれに関連づけた`<label>`のスタイルを変更するっていう遠回しの方法を使ってるけど、他に何か良い方法がありますか？

2024-07-15 08:07 UTC, cp-20 commented on src/shared/components/RadioButton.vue
あー、確かにそうするしかないか、、、じゃあそもそもRadioButtonの実装がいらないという説はありますね (RadioCardでしか使われてないので)

2024-07-15 08:18 UTC, Nattuki commented on src/shared/components/RadioCard.vue
> +      <div :class="$style.btn"></div>
`<RadioButton>`と`<RadioCard>`は機能として全く同じで見た目以外の違いはないと認識しているのでここ`<RadioButton>`を`<RadioCard>`の中に入れるとチェック判定周りのロジックは色々被ったりややこしくなったり気がしますが...？

2024-07-15 08:22 UTC, cp-20 commented on src/shared/components/RadioCard.vue
> +      <div :class="$style.btn"></div>
もともとRadioCardの中で使う想定でFigmaでは書いてたので、RadioButtonを使わないならそもそもコンポーネントとして切り分ける必要はないなと思いました (なので気にしなくて大丈夫です)

2024-07-15 08:23 UTC, Nattuki commented on src/shared/components/RadioButton.vue
僕もそういう気がしてるのでそれなら`<RadioCard>`だけを実装することにして大丈夫ですか（？

2024-07-15 08:24 UTC, Nattuki commented on src/shared/components/RadioCard.vue
> +      <div :class="$style.btn"></div>
把握しました！

2024-07-15 08:26 UTC, cp-20 commented on src/shared/components/RadioButton.vue
OKです！

2024-11-14 08:49 UTC, cp-20 approved these changes

2024-12-18 06:00 UTC, merged