textInput を実装
traPtitech/booQ-v3-UI pull request #61
Opened 2024-12-25 00:37 UTC by soramea

Button 要素ごと template で持ってくることを想定しています
入力欄とそのほかの区別がわかりづらいことがちょっと気になってるんですが、こういうもんなんでしょうか

close: #51

2024-12-26 02:43 UTC, cp-20 reviewed
細々としたところだけど、特にアクセシビリティ的なところは修正して欲しいです！

2024-12-26 02:43 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  outline: 0;
[should] アクセシビリティの観点から `outilne: 0` は外して欲しいです！ (どこにフォーカスが当たっているのかを分かりやすくするため)

2024-12-26 02:43 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  padding: 8px 16px;
[should] 外側の `<div>` に padding 付けちゃうと周辺のエリアが `<input>` じゃなくなっちゃうので、`<input>` の方の padding で対応して欲しいです！

2024-12-26 02:43 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +      :placeholder="props.placeholder"
[imo] `props.placeholder` とかは `placeholder` ってした方が簡単に書けるかも

2024-12-26 02:43 UTC, cp-20 reviewed
細々としたところだけど、特にアクセシビリティ的なところは修正して欲しいです！

2025-05-17 03:20 UTC, soramea commented on src/shared/components/TextInput.vue
> +  outline: 0;
これそのまま外すとサイドアイコンが存在するときに内側だけに線が出てきてしまうので代わりに focus-within で outline を太くしたんですが、input 部分だけが見える方が良いんですかね？

2025-05-17 12:19 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  outline: 0;
ごめん、元のままでOKです！

2025-05-17 12:33 UTC, cp-20 requested changes
色々レビュー漏れがあったのでコメントしました:bow::bow::bow:

2025-05-17 12:33 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  placeholder: string;
placeholder は optional にしてほしい！

2025-05-17 12:33 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  size: number;
size というのは若干直感的ではないかも？ (HTML要素の `<input>` に直接渡してるけど、これは求めているものではなさそう)

雑にやるなら size はなくて良くて、ちゃんとやりたいなら `'sm' | 'md' | 'lg'` みたいな感じでやると良さそうに見えます！

2025-05-17 12:33 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +    </div>
[optional] `<slot>` に直接 `class` を書いた方がスッキリするかも

2025-05-17 12:33 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  outline: 2px solid;
outline は primary-color とかの方が良い感じかも

2025-05-17 12:33 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  border: 1px solid;
`border-color` プロパティが `border` ショートハンドによって上書きされてそう (ref: https://developer.mozilla.org/ja/docs/Web/CSS/border#%E6%A7%8B%E6%88%90%E8%A6%81%E7%B4%A0%E3%81%AE%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3)

border で一緒に指定してあげると良さそう！

2025-05-17 12:33 UTC, cp-20 commented
直したら review request もらえると嬉しいです:bow:

2025-08-09 23:48 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  border:
`1px solid $color-border` で良さそうな気がする！　radius はここでは指定できないので別で指定してあげる必要がある

ref: https://developer.mozilla.org/ja/docs/Web/CSS/border

2025-08-09 23:48 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  opacity: 1;
opacity: 1 は特に意味のないCSSかも…？

2025-08-09 23:48 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  opacity: 1;
opacity: 1 は特に意味のないCSSかも…？

2025-08-10 00:02 UTC, cp-20 commented on src/shared/components/TextInput.vue
> +  border-radius: 1px solid;
border-radius は solid を受け付けない (それは border-style) し、ここで指定すべきは 4px じゃないかな？

2025-08-10 00:46 UTC, merged